### ISSUE TITLE
Card: general issues in card styles

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#138]
Issues:
- `hx-card-joint` removes the right padding when sections are inside vertical groups
- `hx-card-slim` does not apply when card sections are within `hx-card-small` containers
- card sections never wrap (suggest adding `hx-card-horizontal` and using that to apply flex wrapping)

**Comment by c-frater** [comment]
Potential styles for wrapping horizontal cards?
```css
.hx-card-horizontal {
  flex-wrap: wrap;
}

.hx-card-horizontal >.hx-card-group, .hx-card-horizontal > .hx-card-section {
  border-top: 1px solid #e7e7e7;

  /* To account for the border and prevent double width borders */
  margin-top: -1px;
}
```
