### ISSUE TITLE
Notify/Modal: Make the notifications show on top of modals

### ISSUE THREAD

**Issue by c-frater** [ocadotechnology/hexagonjs#69]
For the limited number of times this will happen, it should be reasonable for notifications to be shown on top of modals.

It should just involve the following CSS changes:

```css
.hx-notification-container {
  z-index: 106;
}

body.hx-modal-open .hx-notification-container {
  top: 0;
}
```
